name: Test Script Execution

on:
  push:
    branches:
      - dev*
      - test*
      - improve*

permissions:
  contents: read

jobs:
  test-script:
    name: Test and Run Script
    runs-on: ubuntu-latest
    
    # NO "services:" BLOCK NEEDED
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup All Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq skopeo gawk wget
          
          # Manually install yq, as the script's installer is interactive
          sudo wget -q "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64" -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          yq --version

      - name: Make script executable
        run: chmod +x container-monitor.sh

      - name: Run Functional Tests
        run: |
          echo "Spinning up test container..."
          # This will now use the runner's main Docker daemon
          docker run -d --name=test-monitor-alpine alpine:latest sleep 3600
          echo "Test container 'test-monitor-alpine' is running:"
          docker ps
          
          echo "--- Test 1: --help ---"
          ./container-monitor.sh --help

          echo "--- Test 2: --check-setup ---"
          ./container-monitor.sh --check-setup
          
          echo "--- Test 3: --summary (with a running container) ---"
          ./container-monitor.sh --summary
          
          echo "--- Test 4: Specific container run ---"
          ./container-monitor.sh test-monitor-alpine

          echo "--- Test 5: --logs (against test container) ---"
          ./container-monitor.sh --logs test-monitor-alpine

          echo "--- Test 6: --exclude (against test container) ---"
          ./container-monitor.sh --summary --exclude=test-monitor-alpine
